### ISSUE TITLE
CLI prompt is missing

### ISSUE THREAD

**Issue by suzonch** [Zubax/sapog#45]
Enable CLI prompt for valenok CLi interface

**Comment by silverv** [comment]
Didn't know how to do it, enabling it also raises concerns of spending valuable MCU time on reading in data. I don't know much about how the serial connection works and if there is a hardware buffer. If this turns out to be a performance hog then perhaps it could be first enabled by a Cyphal request and then used.

**Comment by pavel-kirienko** [comment]
CLI consumes zero CPU time unless it is actively used. It works in the original v2 firmware, you just need to make sure that it is not disabled in your branch.

**Comment by silverv** [comment]
Resolved with 33040b0f86fe3b52393894b9a387e802fee2aa85
